apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: metabase.mindmatch.ai
spec:
  secretName: metabase-tls
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - metabase.mindmatch.ai
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - metabase.mindmatch.ai
