kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase
          env:
            - name: MB_DB_USER
              value: "metabase"
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-secrets
                  key: db_password
            - name: MB_DB_HOST
              value: "localhost"
            - name: MB_DB_DBNAME
              value: "metabase"
            - name: MB_DB_TYPE
              value: "postgres"
            - name: MB_DB_PORT
              value: "5432"
          ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=mindmatch-shared-cluster:europe-west2:shared-postgres=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
